version: '3.9'

services:
  db:
    image: postgres:14.3-alpine3.15
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: vic
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_aiohttp
